series: Basic OpenGL with GLFW
title: Drawing a Cube
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: draw a cube instead of a quad.
language: C++
tags:
  - Graphics
  - Math
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: 3D Cameras